doctor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

from account.views import registration_view, logout_view, home, login_view, account_view, must_authenticate_view, cantenter_view, adviced, VerificationView, unadviced, index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', index, name="index"),
    path('', home, name="home"),
    path('unadviced/', unadviced, name="unadviced"),
    path('adviced/', adviced, name="adviced"),
    path('query/', include('query.urls'), name="query"),
    path('profile/', include('userprofile.urls'), name="userprofile"),
    path('comments/', include('comments.urls'), name="comments"),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('cantenter/', cantenter_view, name="cantenter"),
    path('account/', account_view, name="account"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

    path('activate/<uidb64>/<token>', VerificationView.as_view(), name="activate"),

    url(r'session_security/', include('session_security.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

query/urls.py
from django.urls import path
from query.views import create_query_view, docs_not_allowed_view, detail_query_view, edit_query_view, Delete_query

app_name = 'query'

urlpatterns = [
    path('create/', create_query_view, name='create'),
    path('delete/', Delete_query.as_view(), name='delete'),
    path('<slug>/', detail_query_view, name='detail'),
    path('<slug>/edit', edit_query_view, name='edit'),
    path('docs_not_allowed/', docs_not_allowed_view, name='docs_not_allowed'),
]

userprofile/urls.py
from django.urls import path
from userprofile.views import create_profile_view, edit_profile_view, detail_profile_view

app_name = 'userprofile'

urlpatterns = [
    path('create/', create_profile_view, name='create'),
    path('profiles/<slug>/', detail_profile_view, name='detail'),
    path('edit/', edit_profile_view, name='edit'),
]

userprofile/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.db.models.signals import pre_save
from datetime import datetime
from query.models import Query

# Create your models here.


class UserProfile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    phone = models.BigIntegerField(null=True, blank=True, unique=True)
    qualification = models.CharField(max_length=50, null=True, blank=True)
    year_of_ex = models.IntegerField(null=True, blank=True)
    comment_on = models.ManyToManyField(Query, related_name="commented_on")
    date_published = models.DateTimeField(
        auto_now_add=True, verbose_name="date published")
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.user.email


def pre_save_userprofile_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.user.username+str(instance.user.pk))


pre_save.connect(pre_save_userprofile_receiver, sender=UserProfile)

userprofile/forms.py
from django import forms

from userprofile.models import UserProfile


class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'qualification', 'year_of_ex']

    def __init__(self, *args, **kwargs):
        super(CreateProfileForm, self).__init__(*args, **kwargs)
        self.fields['phone'].required = False
        self.fields['qualification'].required = False
        self.fields['year_of_ex'].required = False


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'qualification', 'year_of_ex']

    def __init__(self, *args, **kwargs):
        super(UpdateProfileForm, self).__init__(*args, **kwargs)
        self.fields['phone'].required = False
        self.fields['qualification'].required = False
        self.fields['year_of_ex'].required = False

    def save(self, commit=True):
        query = self.instance

        if self.cleaned_data['phone']:
            query.phone = self.cleaned_data['phone']

        if self.cleaned_data['qualification']:
            query.qualification = self.cleaned_data['qualification']

        if self.cleaned_data['year_of_ex']:
            query.year_of_ex = self.cleaned_data['year_of_ex']

        if commit:
            query.save()
        return query

userprofile/views.py
from django.shortcuts import render, redirect, get_object_or_404
from userprofile.models import UserProfile
from userprofile.forms import CreateProfileForm, UpdateProfileForm
from account.models import Account

# Create your views here.


def create_profile_view(request):

    context = {}

    if not request.user.is_authenticated:
        return redirect('must_authenticate')

    profile = UserProfile.objects.filter(user=request.user)

    if(profile):
        return redirect('cantenter')

    form = CreateProfileForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        user = Account.objects.filter(email=request.user.email).first()
        obj.user = user
        obj.save()
        form = CreateProfileForm()
        return redirect('home')

    context['form'] = form
    profile = UserProfile.objects.filter(user=request.user)
    if profile:
        context['profile'] = profile.first()

    return render(request, "userprofile/create_profile.html", context=context)


def edit_profile_view(request):

    context = {}

    if not request.user.is_authenticated:
        return redirect("must_authenticate")

    profile = get_object_or_404(UserProfile, user=request.user)

    if request.POST:
        form = UpdateProfileForm(request.POST or None,
                                 request.FILES or None, instance=profile)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = 'Updated'
            profile = obj
    form = UpdateProfileForm(
        initial={
            'phone': profile.phone,
            'qualification': profile.qualification,
            'year_of_ex': profile.year_of_ex,
        }
    )
    context['form'] = form
    profile = UserProfile.objects.filter(user=request.user)
    if profile:
        context['profile'] = profile.first()
    return render(request, 'userprofile/edit_profile.html', context=context)


def detail_profile_view(request, slug):
    context = {}
    viewprofile = get_object_or_404(UserProfile, slug=slug)
    if viewprofile.user.atype != 'Doctor':
        if request.user != viewprofile.user:
            if request.user.atype == 'Patient':
                return redirect('cantenter')
    context['viewprofile'] = viewprofile
    profile = UserProfile.objects.filter(user=request.user)
    if profile:
        context['profile'] = profile.first()

    return render(request, 'userprofile/detail_profile.html', context=context)

templates/userprofile/create_profile.html
{% extends 'base.html' %}

{% block body %}

<style type="text/css">
    .create-form {
          width: 100%;
          max-width: 100%;
          padding: 15px;
          margin: auto;
        }
  
        .submit-button{
            max-width: 200px;
        }
  </style>
  
  <div class="container">
      <div class="row">
          <div class="col-lg-7 offset-lg-1">
            <h3 class="mb-3 font-weight-normal text-center">Create your Profile to use this app</h3>
              <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
  
                
                  {% if request.user.atype == 'Patient' %}
                  <div class="form-group">
                      <label for="id_phone">Phone no (use numbers only no alphabets)</label>
                      <input class="form-control" type="number" name="phone" id="id_phone" placeholder="Your Phone no here" required autofocus>
                  </div>
                  {% else %}
  
                  <div class="form-group">
                    <label for="id_qualification">Qualification</label>
                    <input class="form-control" type="text" name="qualification" id="id_qualification" placeholder="Your Qualification here" required autofocus>
                </div>
  
                  <div class="form-group">
                    <label for="id_year_of_ex">Years of Experience</label>
                    <input class="form-control" type="number" name="year_of_ex" id="id_year_of_ex" required placeholder="Your Years of Experience here">
                </div>
                {% endif %}
  
                  <!-- Submit btn -->
                  <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Create</button>
              </form>	
          </div>
      </div>
  </div>

{% endblock body %}

templates/userprofile/detail_profile.html
{% extends 'base.html' %}

{% block body %}
<style>
    .card{
       max-width: 700px; 
    }
    .container{
        padding: 20px;
    }
</style>

<div class="container">
<div class="row">
<div class="card m-auto">
<div class="card-body mt-2 mb-2">
<h2 class="card-title">{{viewprofile.user.username}}</h2>
{% if viewprofile.user.atype != 'Doctor' %}
<p class="card-text">Email - {{viewprofile.user.email}}</p>
{% endif %}
{% if viewprofile.phone %}
<p class="card-text">Phone no - {{viewprofile.phone}}</p>
{% endif %}
{% if viewprofile.qualification %}
<p class="card-text">Qualification - {{viewprofile.qualification}}</p>
{% endif %}
{% if viewprofile.year_of_ex %}
<p class="card-text">Years of Experience - {{viewprofile.year_of_ex}}</p>
{% endif %}
{% if viewprofile.user == request.user %}
<a href="{% url 'userprofile:edit' %}" class="btn btn-primary">Update</a>
{% endif %}
</div>
<div class="card-footer text-muted">
Updated on {{viewprofile.date_updated}} by {{viewprofile.user.username}}
</div>
</div>
</div>
</div>

{% endblock body %}

templates/userprofile/edit_profile.html
{% extends 'base.html' %}


{% block body %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container">
	
		<ul class="nav nav-pills">
		  <li class="nav-item">
			<a class="nav-link" href="{% url 'account' %}">Account</a>
		  </li>
		  <li class="nav-item">
			<a class="nav-link active" href="{% url 'userprofile:edit' %}">Profile</a>
		  </li>
		</ul>
		
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				{% if request.user.atype == 'Patient' %}
				<div class="form-group">
					<label for="id_phone">Phone no</label>
					<input class="form-control" type="number" name="phone" id="id_phone" placeholder="Your Phone here" value="{{form.initial.phone}}" autofocus>
				</div>
                {% else %}
				
				<div class="form-group">
					<label for="id_qualification">Qualification</label>
					<input class="form-control" type="text" name="qualification" id="id_qualification" placeholder="Your Qualification here" value="{{form.initial.qualification}}" autofocus>
				</div>
                
	
				<div class="form-group">
					<label for="id_year_of_ex">Years of Experience</label>
					<input class="form-control" type="number" name="year_of_ex" id="id_year_of_ex" placeholder="Your Years of Experience here" value="{{form.initial.year_of_ex}}">
				</div>
				{% endif %}

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>

{% endblock body %}