comments/urls.py
from django.urls import path
from comments.views import create_comment_view, Delete_comment

app_name = 'comments'

urlpatterns = [
    path('create/<slug>', create_comment_view, name='create'),
    path('delete/<id>/', Delete_comment.as_view(), name='delete'),
]

doctor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

from account.views import registration_view, logout_view, home, login_view, account_view, must_authenticate_view, cantenter_view, adviced, VerificationView, unadviced, index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', index, name="index"),
    path('', home, name="home"),
    path('unadviced/', unadviced, name="unadviced"),
    path('adviced/', adviced, name="adviced"),
    path('query/', include('query.urls'), name="query"),
    path('profile/', include('userprofile.urls'), name="userprofile"),
    path('comments/', include('comments.urls'), name="comments"),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('cantenter/', cantenter_view, name="cantenter"),
    path('account/', account_view, name="account"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

    path('activate/<uidb64>/<token>', VerificationView.as_view(), name="activate"),

    url(r'session_security/', include('session_security.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

query/urls.py
from django.urls import path
from query.views import create_query_view, docs_not_allowed_view, detail_query_view, edit_query_view, Delete_query

app_name = 'query'

urlpatterns = [
    path('create/', create_query_view, name='create'),
    path('delete/', Delete_query.as_view(), name='delete'),
    path('<slug>/', detail_query_view, name='detail'),
    path('<slug>/edit', edit_query_view, name='edit'),
    path('docs_not_allowed/', docs_not_allowed_view, name='docs_not_allowed'),
]

userprofile/urls.py
from django.urls import path
from userprofile.views import create_profile_view, edit_profile_view, detail_profile_view

app_name = 'userprofile'

urlpatterns = [
    path('create/', create_profile_view, name='create'),
    path('profiles/<slug>/', detail_profile_view, name='detail'),
    path('edit/', edit_profile_view, name='edit'),
]

comments/models.py
from django.db import models
from django.conf import settings
from query.models import Query

# Create your models here.


class Comment(models.Model):
    written_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField(max_length=2500, null=False, blank=False)
    commented_on = models.ForeignKey(Query, on_delete=models.CASCADE)
    date_published = models.DateTimeField(
        auto_now_add=True, verbose_name="date published")

    def __str__(self):
        return self.commented_on.slug

query/models.py
from django.db import models
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver
from datetime import datetime
from django.core.exceptions import ValidationError
from account.models import Account


def file_size(value):  # add this to some file where you can import it from
    limit = 2 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 2 MiB.')

# Create your models here.


def upload_loaction(instance, filename, **kwargs):
    file_path = 'queries/{patient_id}/{heading}+{datetiming}+{filename}'.format(
        patient_id=str(instance.patient.id), heading=str(instance.heading), filename=filename, datetiming=datetime.now().strftime("%d/%m/%Y %H:%M:%S")
    )
    return file_path


class Query(models.Model):
    heading = models.TextField(max_length=100, null=False, blank=False)
    body = models.TextField(max_length=2500, null=False, blank=False)
    image = models.FileField(
        upload_to=upload_loaction, null=True, blank=True, validators=[file_size])
    image2 = models.FileField(
        upload_to=upload_loaction, null=True, blank=True, validators=[file_size])
    image3 = models.FileField(
        upload_to=upload_loaction, null=True, blank=True, validators=[file_size])
    image4 = models.FileField(
        upload_to=upload_loaction, null=True, blank=True, validators=[file_size])
    image5 = models.FileField(
        upload_to=upload_loaction, null=True, blank=True, validators=[file_size])
    image6 = models.FileField(
        upload_to=upload_loaction, null=True, blank=True, validators=[file_size])
    image7 = models.FileField(
        upload_to=upload_loaction, null=True, blank=True, validators=[file_size])
    image8 = models.FileField(
        upload_to=upload_loaction, null=True, blank=True, validators=[file_size])
    image9 = models.FileField(
        upload_to=upload_loaction, null=True, blank=True, validators=[file_size])
    image10 = models.FileField(
        upload_to=upload_loaction, null=True, blank=True, validators=[file_size])
    date_published = models.DateTimeField(
        auto_now_add=True, verbose_name="date published")
    date_updated = models.DateTimeField(
        auto_now=True, verbose_name="date updated")
    patient = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    commented_by = models.ManyToManyField(Account, related_name="commented_by")
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.heading


@receiver(post_delete, sender=Query)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)


def pre_save_query_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        info = (instance.heading[30]) if len(
            instance.heading) > 30 else instance.heading
        instance.slug = slugify(instance.patient.username+"-"+info +
                                "-"+datetime.now().strftime("%d/%m/%Y %H:%M:%S"))


pre_save.connect(pre_save_query_receiver, sender=Query)

query/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q

from query.models import Query
from query.forms import CreateQueryForm, UpdateQueryForm
from account.models import Account
from userprofile.models import UserProfile
from comments.views import get_comments
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.views.generic import View

# Create your views here.
COMMENTS_PER_PAGE = 25


def create_query_view(request):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
    if user.atype == 'Doctor':
        return redirect('query:docs_not_allowed')

    form = CreateQueryForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        patient = Account.objects.filter(email=user.email).first()
        obj.patient = patient
        obj.save()
        form = CreateQueryForm()
        return redirect('home')

    context['form'] = form
    profile = UserProfile.objects.filter(user=request.user)
    if profile:
        context['profile'] = profile.first()

    return render(request, "query/create_query.html", context=context)


def docs_not_allowed_view(request):
    context = {}
    profile = UserProfile.objects.filter(user=request.user)
    if profile:
        context['profile'] = profile.first()
    return render(request, 'query/docs_not_allowed.html', context=context)


def detail_query_view(request, slug):
    context = {}
    query = get_object_or_404(Query, slug=slug)
    if not request.user.is_authenticated:
        return redirect('must_authenticate')
    if request.user != query.patient:
        if request.user.atype == 'Patient':
            return redirect('cantenter')
    context['query'] = query
    profile = UserProfile.objects.filter(user=request.user)
    seeing_profile = UserProfile.objects.filter(user=query.patient)
    if seeing_profile:
        context['seeing_profile'] = seeing_profile.first()
    if profile:
        context['profile'] = profile.first()

    queries = get_comments(query)

    page = request.GET.get('page', 1)
    query_paginator = Paginator(queries, COMMENTS_PER_PAGE)

    try:
        queries = query_paginator.page(page)
    except PageNotAnInteger:
        queries = query_paginator.page(COMMENTS_PER_PAGE)
    except EmptyPage:
        queries = query_paginator.page(query_paginator.num_pages)

    context['queries'] = queries

    return render(request, 'query/detail_query.html', context=context)


def edit_query_view(request, slug):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect("must_authenticate")
    query = get_object_or_404(Query, slug=slug)
    if user != query.patient:
        return redirect("cantenter")

    if request.POST:
        form = UpdateQueryForm(request.POST or None,
                               request.FILES or None, instance=query)
        if form.is_valid():
            obj = form.save(commit=False)
            if request.POST.get('clear_image_image'):
                obj.image = None
            if request.POST.get('clear_image_image2'):
                obj.image2 = None
            if request.POST.get('clear_image_image3'):
                obj.image3 = None
            if request.POST.get('clear_image_image4'):
                obj.image4 = None
            if request.POST.get('clear_image_image5'):
                obj.image5 = None
            if request.POST.get('clear_image_image6'):
                obj.image6 = None
            if request.POST.get('clear_image_image7'):
                obj.image7 = None
            if request.POST.get('clear_image_image8'):
                obj.image8 = None
            if request.POST.get('clear_image_image9'):
                obj.image9 = None
            if request.POST.get('clear_image_image10'):
                obj.image10 = None
            obj.save()
            context['success_message'] = 'Updated'
            query = obj
        else:
            errors = []
            for field in form:
                for error in field.errors:
                    errors.append(error)
            context['errors'] = errors
    form = UpdateQueryForm(
        initial={
            'heading': query.heading,
            'body': query.body,
            'image': query.image or None,
            'image2': query.image2 or None,
            'image3': query.image3 or None,
            'image4': query.image4 or None,
            'image5': query.image5 or None,
            'image6': query.image6 or None,
            'image7': query.image7 or None,
            'image8': query.image8 or None,
            'image9': query.image9 or None,
            'image10': query.image10 or None,
        }
    )
    context['form'] = form
    profile = UserProfile.objects.filter(user=request.user)
    if profile:
        context['profile'] = profile.first()
    return render(request, 'query/edit_query.html', context=context)


def get_query_queryset(request, query=None, advice=False, unadvice=False):
    aqset = []
    unqset = []
    profile = UserProfile.objects.filter(user=request.user)
    if profile:
        profile = profile.first()
    if query == "":
        if(request.user.atype == 'Doctor'):
            if advice == True:
                aqs = Query.objects.all()
                for aq in aqs:
                    if aq in profile.comment_on.all():
                        aqset.append(aq)
                return list(set(aqset))
            if unadvice == True:
                unqset = Query.objects.filter(commented_by=None)
                return list(set(unqset))
            return(Query.objects.all())
        else:
            return(Query.objects.filter(patient=request.user))

    queryset = []
    queries = query.split(" ")

    if(request.user.atype == 'Doctor'):
        if advice == True:
            for q in queries:
                posts = Query.objects.filter(
                    Q(heading__icontains=q) |
                    Q(body__icontains=q) |
                    Q(patient__username__icontains=q)
                ).distinct()

            for post in posts:
                if post in profile.comment_on.all():
                    queryset.append(post)
        elif unadvice == True:
            for q in queries:
                posts = Query.objects.filter(
                    Q(heading__icontains=q) |
                    Q(body__icontains=q) |
                    Q(patient__username__icontains=q)
                ).distinct()

            for post in posts:
                if post.commented_by == None:
                    queryset.append(post)

        else:
            for q in queries:
                posts = Query.objects.filter(
                    Q(heading__icontains=q) |
                    Q(body__icontains=q) |
                    Q(patient__username__icontains=q)
                ).distinct()

            for post in posts:
                queryset.append(post)
    else:
        for q in queries:
            posts = Query.objects.filter(
                Q(heading__icontains=q) | Q(body__icontains=q)).distinct()

        for post in posts:
            if post.patient == request.user:
                queryset.append(post)

    return list(set(queryset))


class Delete_query(View):

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            query_ids = request.POST.getlist('id[]')
            for id in query_ids:
                query = Query.objects.get(pk=id)
                query.delete()
            return redirect('home')

templates/query/create_query.html
{% extends 'base.html' %}

{% block body %}

<style type="text/css">
    .create-form {
          width: 100%;
          max-width: 100%;
          padding: 15px;
          margin: auto;
        }
  
        .submit-button{
            max-width: 200px;
        }
  </style>
  
  <div class="container">
      <div class="row">
          <div class="col-lg-7 offset-lg-1">
              <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
  
                  <div class="form-group">
                    <label for="id_heading">Heading</label>
                    <input class="form-control" type="text" name="heading" id="id_heading" placeholder="Heading" required autofocus>
                </div>
  
                  <!-- Body -->
                  <div class="form-group">
                      <label for="id_body">Content</label>
                      <textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="Write your query here..." required></textarea>
                  </div>
                  {% for field in form %}
                <p>
            {% for error in field.errors %}
            <p style="color: red;">{{field.name}} : {{error}}</p>
            {% endfor %}
                </p>
                {% endfor %}
                <p>
                    Upload limit 2 mb for each file
                </p>
                  <!-- Image -->
                  <div class="form-group">
                      <label for="id_image">Upload Report 1 if Any (pdf/image)</label>
                      <input  type="file" name="image" id="id_image" accept="image/jpeg,image/png,application/pdf">
                  </div>
                  <a class="btn btn-primary mb-4" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Upload More Reports</a>

                  <div class="collapse multi-collapse" id="multiCollapseExample1">
                  <div class="form-group">
                    <label for="id_image2">Upload Report 2 if Any (pdf/image)</label>
                    <input  type="file" name="image2" id="id_image2" accept="image/jpeg,image/png,application/pdf">
                </div>

                <div class="form-group">
                    <label for="id_image3">Upload Report 3 if Any (pdf/image)</label>
                    <input  type="file" name="image3" id="id_image3" accept="image/jpeg,image/png,application/pdf">
                </div>

                <div class="form-group">
                    <label for="id_image4">Upload Report 4 if Any (pdf/image)</label>
                    <input  type="file" name="image4" id="id_image4" accept="image/jpeg,image/png,application/pdf">
                </div>

                <div class="form-group">
                    <label for="id_image5">Upload Report 5 if Any (pdf/image)</label>
                    <input  type="file" name="image5" id="id_image5" accept="image/jpeg,image/png,application/pdf">
                </div>

                <div class="form-group">
                    <label for="id_image6">Upload Report 6 if Any (pdf/image)</label>
                    <input  type="file" name="image6" id="id_image6" accept="image/jpeg,image/png,application/pdf">
                </div>

                <div class="form-group">
                    <label for="id_image7">Upload Report 7 if Any (pdf/image)</label>
                    <input  type="file" name="image7" id="id_image7" accept="image/jpeg,image/png,application/pdf">
                </div>

                <div class="form-group">
                    <label for="id_image8">Upload Report 8 if Any (pdf/image)</label>
                    <input  type="file" name="image8" id="id_image8" accept="image/jpeg,image/png,application/pdf">
                </div>

                <div class="form-group">
                    <label for="id_image9">Upload Report 9 if Any (pdf/image)</label>
                    <input  type="file" name="image9" id="id_image9" accept="image/jpeg,image/png,application/pdf">
                </div>

                <div class="form-group">
                    <label for="id_image10">Upload Report 10 if Any (pdf/image)</label>
                    <input  type="file" name="image10" id="id_image10" accept="image/jpeg,image/png,application/pdf">
                </div>
            </div>

  
                  <!-- Submit btn -->
                  <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
              </form>	
          </div>
      </div>
  </div>

{% endblock body %}

templates/query/detail_query.html
{% extends 'base.html' %}

{% block body %}
<style>
    .card{
       max-width: 700px; 
    }
    .container{
        padding: 20px;
    }
    .create-form {
          width: 100%;
          max-width: 100%;
          padding: 15px;
          margin: auto;
        }
  
        .submit-button{
            max-width: 200px;
        }
        .pl-0{
        padding-left: 0;
    }
    .mb-0{
        margin-bottom: 0;
    }
    .comment-height{
        height: 30vh;
    }
</style>

<div class="container">
<div class="row">
<div class="card m-auto">
   
<div class="card-body mt-2 mb-2">
    {% if query.image %}
    <p>Report Link 1 - <a href="{{query.image.url}}" target="_blank">Click Here</a></p>
    {% endif %}
    {% if query.image2 %}
    <p>Report Link 2 - <a href="{{query.image2.url}}" target="_blank">Click Here</a></p>
    {% endif %}
    {% if query.image3 %}
    <p>Report Link 3 - <a href="{{query.image3.url}}" target="_blank">Click Here</a></p>
    {% endif %}
    {% if query.image4 %}
    <p>Report Link 4 - <a href="{{query.image4.url}}" target="_blank">Click Here</a></p>
    {% endif %}
    {% if query.image5 %}
    <p>Report Link 5 - <a href="{{query.image5.url}}" target="_blank">Click Here</a></p>
    {% endif %}
    {% if query.image6 %}
    <p>Report Link 6 - <a href="{{query.image6.url}}" target="_blank">Click Here</a></p>
    {% endif %}
    {% if query.image7 %}
    <p>Report Link 7 - <a href="{{query.image7.url}}" target="_blank">Click Here</a></p>
    {% endif %}
    {% if query.image8 %}
    <p>Report Link 8 - <a href="{{query.image8.url}}" target="_blank">Click Here</a></p>
    {% endif %}
    {% if query.image9 %}
    <p>Report Link 9 - <a href="{{query.image9.url}}" target="_blank">Click Here</a></p>
    {% endif %}
    {% if query.image10 %}
    <p>Report Link 10 - <a href="{{query.image10.url}}" target="_blank">Click Here</a></p>
    {% endif %}
<h2 class="card-title">{{query.heading}}</h2>
<p class="card-text">{{query.body}}</p>
{% if query.patient == request.user %}
<a href="{% url 'query:edit' query.slug %}" class="btn btn-primary">Edit</a>
{% endif %}
</div>
<div class="card-footer text-muted">
Updated on {{query.date_updated}} by {{query.patient.email}} Phone: {{seeing_profile.phone}}
</div>
</div>
</div>

<div class="row">
    <div class="col-lg-12 comment-height">
    <h3 class="mb-3 font-weight-normal text-center">Comments:</h3>
    {% if queries %}
    <ul class="pl-0 overflow-auto" style="height: 100%;">
        {% for comment in queries %}
            <li class="list-group-item {% if comment.written_by == request.user %}text-right{% endif %}" >
                <p class="mb-0"><a href="{% url 'userprofile:detail' comment.slug %}">{{comment.written_by.username}}</a> : {{comment.text}} {% if comment.written_by == request.user %}<a href="{% url 'comments:delete' comment.pk %}">Delete</a>{% endif %}</p>
                <p class="text-muted small mb-0">{{comment.date_published}}</p>
            </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No comments yet</p>
    {% endif %}
    {% if queries.paginator.num_pages != 1 %}
    {% include 'snippets/comment_pagination.html' with queries=queries %}
    {% endif %}
</div>
</div>

<div class="row" style="margin-top: 10vh;">
    <div class="col-lg-12">
        <form class="create-form" method="post" action="/comments/create/{{query.slug}}" enctype="multipart/form-data">{% csrf_token %}

            <div class="row">
            <div class="col-lg-10">
                <div class="form-group">
                    <textarea class="form-control" name="text" id="id_text" cols="30" rows="2" required autofocus placeholder="Comment here"></textarea>
                </div>
            </div>
            
            <div class="col-lg-2">
                <!-- Submit btn -->
            <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Comment</button>
            </div>
        </div>
            
        </form>	
    </div>
</div>

</div>

{% endblock body %}

templates/query/docs_not_allowed.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
<div class="d-flex flex-column">
<p class="m-auto">Docs not allowed in this page.</p>
<p class="m-auto">
<a href="{% url 'logout' %}">Logout</a> or
</p>
</div>
</div>

{% endblock body %}

templates/query/edit_query.html
{% extends 'base.html' %}


{% block body %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_heading">heading</label>
					<input class="form-control" type="text" name="heading" id="id_heading" placeholder="heading" value="{{form.initial.heading}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="Your Query here..." 
					required>{{form.initial.body}}</textarea>
				</div>
				{% for field in form %}
                <p>
            {% for error in field.errors %}
            <p style="color: red;">{{field}} : {{error}}</p>
            {% endfor %}
                </p>
                {% endfor %}
				<p>
                    Upload limit 2 mb for each file
                </p>

				<!-- Image -->
				<div class="form-group">
                    <label for="id_image">Change Report 1 
						{% if form.initial.image %}
						Previous Report 1 - <a href="{{form.initial.image.url}}" target="_blank">Click Here</a>
						{% endif %}
					</label>
                    <br>
                    <input  type="file" name="image" id="id_image" accept="image/jpeg,image/png,application/pdf">
				</div>
				<a class="btn btn-primary mb-4" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">See More Reports</a>

                  <div class="collapse multi-collapse" id="multiCollapseExample1">
				<div class="form-group">
                    <label for="id_image2">Change Report 2
						{% if form.initial.image2 %}
						Previous Report 2 - <a href="{{form.initial.image2.url}}" target="_blank">Click Here</a>
						{% endif %}
					</label>
                    <br>
                    <input  type="file" name="image2" id="id_image2" accept="image/jpeg,image/png,application/pdf">
				</div>
				
				<div class="form-group">
                    <label for="id_image3">Change Report 3
						{% if form.initial.image3 %}
						Previous Report 3 - <a href="{{form.initial.image3.url}}" target="_blank">Click Here</a>
						{% endif %}
					</label>
                    <br>
                    <input  type="file" name="image3" id="id_image3" accept="image/jpeg,image/png,application/pdf">
				</div>
				
				<div class="form-group">
                    <label for="id_image4">Change Report 4
						{% if form.initial.image4 %}
						Previous Report 4 - <a href="{{form.initial.image4.url}}" target="_blank">Click Here</a>
						{% endif %}
					</label>
                    <br>
                    <input  type="file" name="image4" id="id_image4" accept="image/jpeg,image/png,application/pdf">
				</div>
				
				<div class="form-group">
                    <label for="id_image5">Change Report 5
						{% if form.initial.image5 %}
						Previous Report 5 - <a href="{{form.initial.image5.url}}" target="_blank">Click Here</a>
						{% endif %}
					</label>
                    <br>
                    <input  type="file" name="image5" id="id_image5" accept="image/jpeg,image/png,application/pdf">
				</div>
				
				<div class="form-group">
                    <label for="id_image6">Change Report 6
						{% if form.initial.image6 %}
						Previous Report 6 - <a href="{{form.initial.image6.url}}" target="_blank">Click Here</a>
						{% endif %}
					</label>
                    <br>
                    <input  type="file" name="image6" id="id_image6" accept="image/jpeg,image/png,application/pdf">
				</div>
				
				<div class="form-group">
                    <label for="id_image7">Change Report 7
						{% if form.initial.image7 %}
						Previous Report 7 - <a href="{{form.initial.image7.url}}" target="_blank">Click Here</a>
						{% endif %}
					</label>
                    <br>
                    <input  type="file" name="image7" id="id_image7" accept="image/jpeg,image/png,application/pdf">
				</div>
				
				<div class="form-group">
                    <label for="id_image8">Change Report 8
						{% if form.initial.image8 %}
						Previous Report 8 - <a href="{{form.initial.image8.url}}" target="_blank">Click Here</a>
						{% endif %}
					</label>
                    <br>
                    <input  type="file" name="image8" id="id_image8" accept="image/jpeg,image/png,application/pdf">
				</div>
				
				<div class="form-group">
                    <label for="id_image9">Change Report 9
						{% if form.initial.image9 %}
						Previous Report 9 - <a href="{{form.initial.image9.url}}" target="_blank">Click Here</a>
						{% endif %}
					</label>
                    <br>
                    <input  type="file" name="image9" id="id_image9" accept="image/jpeg,image/png,application/pdf">
				</div>
				
				<div class="form-group">
                    <label for="id_image10">Change Report 10
						{% if form.initial.image10 %}
						Previous Report 10 - <a href="{{form.initial.image10.url}}" target="_blank">Click Here</a>
						{% endif %}
					</label>
                    <br>
                    <input  type="file" name="image10" id="id_image10" accept="image/jpeg,image/png,application/pdf">
				</div>
				</div>
				

				{% for error in errors %}
							<p style="color: red">{{ error }}</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>

{% endblock body %}

{% block script %}
<script type="text/javascript">
	$(document).ready(function() {
		$('input[type=file]').each(function() {
			$(this).after(' <input type="checkbox" name="clear_image_'+$(this).attr('name')+'"/> Clear');
		});
	});
	</script>
{% endblock script %}