doctor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

from account.views import registration_view, logout_view, home, login_view, account_view, must_authenticate_view, cantenter_view, adviced, VerificationView, unadviced, index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', index, name="index"),
    path('', home, name="home"),
    path('unadviced/', unadviced, name="unadviced"),
    path('adviced/', adviced, name="adviced"),
    path('query/', include('query.urls'), name="query"),
    path('profile/', include('userprofile.urls'), name="userprofile"),
    path('comments/', include('comments.urls'), name="comments"),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('cantenter/', cantenter_view, name="cantenter"),
    path('account/', account_view, name="account"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

    path('activate/<uidb64>/<token>', VerificationView.as_view(), name="activate"),

    url(r'session_security/', include('session_security.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

query/urls.py
from django.urls import path
from query.views import create_query_view, docs_not_allowed_view, detail_query_view, edit_query_view, Delete_query

app_name = 'query'

urlpatterns = [
    path('create/', create_query_view, name='create'),
    path('delete/', Delete_query.as_view(), name='delete'),
    path('<slug>/', detail_query_view, name='detail'),
    path('<slug>/edit', edit_query_view, name='edit'),
    path('docs_not_allowed/', docs_not_allowed_view, name='docs_not_allowed'),
]

userprofile/urls.py
from django.urls import path
from userprofile.views import create_profile_view, edit_profile_view, detail_profile_view

app_name = 'userprofile'

urlpatterns = [
    path('create/', create_profile_view, name='create'),
    path('profiles/<slug>/', detail_profile_view, name='detail'),
    path('edit/', edit_profile_view, name='edit'),
]

templates/snippets/base_css.html
<style>
    body{
        background-color: #f2f2f2;
    }
</style>

templates/snippets/comment_pagination.html
<div class="d-flex flex-column m-auto pagination mt-5">
    <nav aria-label="Page navigation">
    <ul class="pagination pg-grey justify-content-center">
        {% if queries.has_previous %}
        <li class="page-item">
            <a class="page-link"  href="?{% if user_query %}q={{user_query}}&{% endif %}page=1">&laquo; First</a>
          </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ queries.previous_page_number }}">&laquo; Previous</a>
            </li>
        {% endif %}

        {% if queries.paginator.num_pages != 1 %}
        {% for i in queries.paginator.page_range %}
            {% if queries.number == i %}
                <li class="page-item active"><a class="page-link">{{ i }}</a></li>
                {% elif i < queries.number|add:"5" and i > queries.number|add:"-5" %}
                <li class="page-item" ><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% endif %}
        
        {% if queries.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ queries.next_page_number }}">Next</a>
            </li>
            <li class="page-item">
              <a class="page-link"  href="?page={{ queries.paginator.num_pages }}">Last &raquo;</a>
            </li>
        {% endif %}
    </ul>
    </nav>
    </div>
    <!-- end pagination-->

templates/snippets/footer.html
<div style="padding: 2rem;" class="text-center footer bg-white shadow-lg">
    <p>Medwise | Copyright 2020</p>
    <p><a href='https://www.freepik.com/photos/people'>People photo created by pressfoto - www.freepik.com</a></p>  
</div>


<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
{% include 'session_security/all.html' %}

templates/snippets/header.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<style>
  
@media (min-width: 768px) {
  html {
    font-size: 16px;
  }
}

.container {
  max-width: 960px;
}

.pricing-header {
  max-width: 700px;
}

.card-deck .card {
  min-width: 220px;
}
.search-bar{
  max-width: 500px;
  width: 100%;
}
</style>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">
        {% if request.user.is_authenticated %}
        {% if profile %}
        <p><a href="{% url 'userprofile:detail' profile.slug %}">Hello {{request.user.username}}</a></p>
        {% else %}
        <p>Hello {{request.user.username}}</p>
        {% endif %}
        {% else %}
        <p><a href="{% url 'index' %}">Medwise</a></p>
        {% endif %}
    </h5>

    {% if request.user.is_authenticated %}
    <div class="search-bar mt-sm-2 mr-2">
      <form method="GET">
        <input type="text" class="form-control" name="q" id="id_q" placeholder="Search...">
      </form>
    </div>
    {% endif %}

    <nav class="my-2 my-md-0 mr-md-3">
        {% if request.user.is_authenticated %}
        <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
        {% if request.user.atype == 'Doctor' %}
        {% if profile %}
        <a class="p-2 text-dark" href="{% url 'adviced' %}">My Quieries</a>
        <a class="p-2 text-dark" href="{% url 'unadviced' %}">Unattended Quieries</a>
        {% endif %}
        {% endif %}
        <a class="p-2 text-dark" href="{% url 'account' %}">Account</a>
        {% if profile %}
        {% else %}
        <a class="p-2 text-dark" href="{% url 'userprofile:create' %}">Create Profile</a>
        {% endif %}
      <a class="p-2 text-dark" href="{% url 'logout' %}">Logout</a>
      {{ sessexp }}
        {% else %}
        <a class="btn btn-outline-primary" href="{% url 'register' %}">Register</a>
        <a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
        {% endif %}
      
    </nav>
  </div>
  

  <script>
    document.getElementById("id_q").value="{{user_query}}";
  </script>
  

templates/snippets/query_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
    <nav aria-label="Page navigation">
    <ul class="pagination pg-grey justify-content-center">
        {% if queries.has_previous %}
        <li class="page-item">
            <a class="page-link"  href="?{% if user_query %}q={{user_query}}&{% endif %}page=1">&laquo; First</a>
          </li>
            <li class="page-item">
              <a class="page-link" href="?{% if user_query %}q={{user_query}}&{% endif %}page={{ queries.previous_page_number }}">Previous</a>
            </li>
        {% endif %}
    
        {% if queries.paginator.num_pages != 1 %}
        {% for i in queries.paginator.page_range %}
            {% if queries.number == i %}
                <li class="page-item active"><a class="page-link">{{ i }}</a></li>
            {% elif i < queries.number|add:"5" and i > queries.number|add:"-5" %}
                <li class="page-item" ><a class="page-link" href="?{% if user_query %}q={{user_query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% endif %}
        
        {% if queries.has_next %}
            <li class="page-item">
              <a class="page-link" href="?{% if user_query %}q={{user_query}}&{% endif %}page={{ queries.next_page_number }}">Next</a>
            </li>
            <li class="page-item">
              <a class="page-link"  href="?{% if user_query %}q={{user_query}}&{% endif %}page={{ queries.paginator.num_pages }}">Last &raquo;</a>
            </li>
        {% endif %}
    </ul>
    </nav>
    </div>
    <!-- end pagination-->