doctor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

from account.views import registration_view, logout_view, home, login_view, account_view, must_authenticate_view, cantenter_view, adviced, VerificationView, unadviced, index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', index, name="index"),
    path('', home, name="home"),
    path('unadviced/', unadviced, name="unadviced"),
    path('adviced/', adviced, name="adviced"),
    path('query/', include('query.urls'), name="query"),
    path('profile/', include('userprofile.urls'), name="userprofile"),
    path('comments/', include('comments.urls'), name="comments"),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('cantenter/', cantenter_view, name="cantenter"),
    path('account/', account_view, name="account"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

    path('activate/<uidb64>/<token>', VerificationView.as_view(), name="activate"),

    url(r'session_security/', include('session_security.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

query/urls.py
from django.urls import path
from query.views import create_query_view, docs_not_allowed_view, detail_query_view, edit_query_view, Delete_query

app_name = 'query'

urlpatterns = [
    path('create/', create_query_view, name='create'),
    path('delete/', Delete_query.as_view(), name='delete'),
    path('<slug>/', detail_query_view, name='detail'),
    path('<slug>/edit', edit_query_view, name='edit'),
    path('docs_not_allowed/', docs_not_allowed_view, name='docs_not_allowed'),
]

templates/adviced.html
{% extends 'base.html' %}

{% block body %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.blog-posts{
		max-width: 500px;
		width: 100%;
		margin: auto;
	}
    .pl-0{
        padding-left: 0;
    }
</style>

<div class="container">
<div class="row">

<div class="left-column col-lg-7 col-sm-12 offset-lg-1">

<div class="blog-posts">
<h3 class="mb-3 font-weight-normal text-center">My Queries</h3>
{% if queries %}
<ul class="pl-0">
	{% for query in queries %}
		<a href="{% url 'query:detail' query.slug %}" style="text-decoration: none;"><li class="list-group-item" >{{query.patient.username}} : {{query}}</li></a>
	{% endfor %}
</ul>
{% else %}
<p>No Advised queries Found</p>
{% endif %}
</div>
{% include 'snippets/query_pagination.html' with queries=queries %}
</div>

</div>

</div>
</div>

{% endblock body %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Medwise</title>
    {% include 'snippets/header.html' %}
    {% include 'snippets/base_css.html' %}
</head>
<body>
    <style>
        .main{
           min-height: 100vh; 
           height: 100%;
        }
    </style>
    <div class="main">
        {% block body %}
{% endblock body %}
    </div>

{% include 'snippets/footer.html' %}
{% block script %}
{% endblock script %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block body %}
<style type="text/css">

	.create-post-bar{
		margin-bottom:20px;
	}
	.blog-posts{
		width: 100%;
		margin: auto;
	}
	.pl-0{
        padding-left: 0;
    }
</style>

<div class="container">
<div class="row">

<div class="col-lg-12">
	{% if request.user.atype == 'Patient' %}

<div class="create-post-bar text-center">
<p>Click on the button below to Enter your Query</p>
<a class="btn btn-outline-primary" href="{% url 'query:create' %}">Enter Query</a>
</div>

{% endif %}

<div class="blog-posts">
	{% if request.user.atype == 'Patient' %}
<h3 class="mb-3 font-weight-normal text-center">Your Existing Queries</h3>
{% else %}
<h3 class="mb-3 font-weight-normal text-center">Queries</h3>
{% endif %}
{% if queries %}
{% csrf_token %}
{% if request.user.atype != 'Doctor' %}
<button type="submit" id="delete_btn" class="btn btn-danger mb-4">Delete</button>
{% endif %}
<ul class="pl-0">
	{% for query in queries %}
	
		{% if request.user.atype == 'Patient' %}
		<li class="list-group-item" id="{{query.pk}}" ><input type="checkbox" class="mr-4" name="query_id[]" value="{{query.pk}}" id='delete_query'><a href="{% url 'query:detail' query.slug %}" style="text-decoration: none;">{{query}}</a><a style="float: right;" href="{% url 'query:edit' query.slug %}">Edit</a></li>
		{% else %}
		<a href="{% url 'query:detail' query.slug %}" style="text-decoration: none;"><li class="list-group-item" >{{query.patient.username}} : {{query}}</li></a>
		{% endif %}
	
	{% endfor %}
</ul>
{% else %}
<center><p>No queries Found</p></center>
{% endif %}
</div>
{% include 'snippets/query_pagination.html' with queries=queries %}
</div>

</div>
</div>

{% endblock body %}

{% block script %}
<script>
	$(document).ready(function(){
		$('#delete_btn').click(function(){
			if(confirm("Are you sure to delete this items ?")){
				var id=[];
				var csrf=$('input[name=csrfmiddlewaretoken]').val()
				$(':checkbox:checked').each(function(i){
					id[i]=$(this).val();
				})
				if(id.length ===0){
					alert("Please select items to delete ?");
				}else{
					$.ajax({
						url:"/query/delete/",
						method:"POST",
						data:{
							id,
							csrfmiddlewaretoken:csrf
						},
					success:function(response){
						for(var i=0; i<id.length;i++){
							$('li#'+id[i]+'').fadeOut('slow');
						}
					}
				})
			}
		}})});
</script>

{% endblock script %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<style>
    hr.style-eight {
    overflow: visible; /* For IE */
    padding: 0;
    border: none;
    border-top: medium double #333;
    color: #333;
    text-align: center;
}
hr.style-eight:after {
    content: "§";
    display: inline-block;
    position: relative;
    top: -0.7em;
    font-size: 1.5em;
    padding: 0 0.25em;
    background: #f2f2f2;
}
img {
  max-width: 100%;
  height: auto;
}
@media only screen and (min-width: 768px) {
    .mt-50{
        margin-top: 20%;
    }
}
</style>
<div class="container">
    <div class="row">
        <div class="col-lg-6 text-center">
            <h1 style="font-size: 2.75rem; font-weight: 600; color: rgb(6, 6, 95);" class="mt-50">Welcome to Medwise</h1>
            <h4 style="color: rgb(6, 6, 95);">Giving back to our community</h4>
            <hr class="style-eight" style="margin-top: 2rem;">
            <h1 style="font-size: 2rem; font-weight: 500;color: rgb(6, 6, 95);" class="mt-4">Our Vision</h1>
            <h4 style="font-weight: 360;">To have a Society where Patients are not subjected to unnecessary medical procedures to extract money from them.</h4>
            <h1 style="font-size: 2rem; font-weight: 500;color: rgb(6, 6, 95);" class="mt-4">Our Mission</h1>
            <h4 style="font-weight: 360;">We are a group of Volunteer Doctors and Technocrats who provide and facilitate 2nd opinion to patients/ caretakers, online and free.</h4>
        </div>
        <div class="col-lg-6 text-center">
            <img src="{% static 'proud-doctor-with-stethoscope.jpg' %}" alt="">
        </div>
    </div>
    <p style="font-weight: bolder;"> <u>Disclaimer</u> </p>
    <p>The doctors here provide you with the best advise based on your (Patient/Attendent) description of the problem, the reports uploaded and current practices of medicine available. The advice seeker is free to seek another opinion outside this forum and this forum or the volunteering doctors can not be held accountable for outcome of the advise provided herein or through this forum. 
        This service is done with the best intentions of the community in mind and is provided free. Our Volunteer doctors try their best to reply to queries on time, however do to their busy schedule you may face delay at times.
        </p>

</div>
{% endblock body %}

templates/something_went_wrong.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
<div class="d-flex flex-column">
<p class="m-auto">Sorry something went wrong!</p>
</div>
</div>

{% endblock body %}

templates/unadviced.html
{% extends 'base.html' %}

{% block body %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.blog-posts{
		max-width: 500px;
		width: 100%;
		margin: auto;
	}
    .pl-0{
        padding-left: 0;
    }
</style>

<div class="container">
<div class="row">

<div class="left-column col-lg-7 col-sm-12 offset-lg-1">

<div class="blog-posts">
<h3 class="mb-3 font-weight-normal text-center">Unadviced Queries</h3>
{% if queries %}
<ul class="pl-0">
	{% for query in queries %}
		<a href="{% url 'query:detail' query.slug %}" style="text-decoration: none;"><li class="list-group-item" >{{query.patient.username}} : {{query}}</li></a>
	{% endfor %}
</ul>
{% else %}
<p>No Advised queries Found</p>
{% endif %}
</div>
{% include 'snippets/query_pagination.html' with queries=queries %}
</div>

</div>

</div>
</div>

{% endblock body %}